- EllipticEnvelope
- IsolationForest
- LOF
- DBSCAN
- OneClassSVM

In [ ]:
import pandas as pd
import numpy as np


In [2]:
path = '/Users/vladislavpleshko/Documents/VS Code/before/amazinum/data/creditcard 2.csv'
df = pd.read_csv(path)
df.drop(columns=['Time'], inplace=True)
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 30 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   V1      284807 non-null  float64
 1   V2      284807 non-null  float64
 2   V3      284807 non-null  float64
 3   V4      284807 non-null  float64
 4   V5      284807 non-null  float64
 5   V6      284807 non-null  float64
 6   V7      284807 non-null  float64
 7   V8      284807 non-null  float64
 8   V9      284807 non-null  float64
 9   V10     284807 non-null  float64
 10  V11     284807 non-null  float64
 11  V12     284807 non-null  float64
 12  V13     284807 non-null  float64
 13  V14     284807 non-null  float64
 14  V15     284807 non-null  float64
 15  V16     284807 non-null  float64
 16  V17     284807 non-null  float64
 17  V18     284807 non-null  float64
 18  V19     284807 non-null  float64
 19  V20     284807 non-null  float64
 20  V21     284807 non-null  float64
 21  V22     28

In [ ]:
df.drop_duplicates(inplace=True)
X = df.drop(columns=['Class'])
y_true = df['Class']
print(df['Class'].value_counts())
X.head()


Class
0    275190
1       473
Name: count, dtype: int64


V1        V2        V3        V4        V5        V6        V7  \
0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9       V10  ...       V20       V21       V22       V23  \
0  0.098698  0.363787  0.090794  ...  0.251412 -0.018307  0.277838 -0.110474   
1  0.085102 -0.255425 -0.166974  ... -0.069083 -0.225775 -0.638672  0.101288   
2  0.247676 -1.514654  0.207643  ...  0.524980  0.247998  0.771679  0.909412   
3  0.377436 -1.387024 -0.054952  ... -0.208038 -0.108300  0.005274 -0.190321   
4 -0.270533  0.817739  0.753074  ...  0.408542 -0.009431  0.798278 -0.137458   

        V24       V25       V26       V27       V28  Amount  
0  0.066928  0.128539 -0.189115  0.133558 -0.021053  149.62  
1 -0.339846  0.167170  0.125895 -0.008983  0.014724    2.69  
2 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  378.66  
3 -1.175575  0.647376 -0.221929  0.062723  0.061458  123.50  
4  0.141267 -0.206010  0.502292  0.219422  0.215153   69.99  

[5 rows x 29 columns]

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.neighbors import LocalOutlierFactor
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.covariance import EllipticEnvelope
from sklearn.ensemble import IsolationForest
from sklearn.svm import OneClassSVM
from sklearn.metrics import classification_report, roc_auc_score, accuracy_score, precision_recall_curve, auc, confusion_matrix, make_scorer, f1_score


In [ ]:
X_scaled = StandardScaler().fit_transform(X)
X_pca = PCA(n_components=2).fit_transform(X_scaled)

X_train, X_test, y_train, y_test = train_test_split(X_pca, y_true,
                                                    test_size=0.25,
                                                    stratify=y_true)
for name, arr in zip(['X_train','X_test','y_train','y_test'],[X_train, X_test, y_train, y_test]):
  print(f'{name}: {arr.shape}')


X_train: (206747, 2)
X_test: (68916, 2)
y_train: (206747,)
y_test: (68916,)


In [ ]:
def run_ee():

  pipeline_ee = Pipeline([
      ('scaler', StandardScaler()),
      ('pca', PCA(n_components=0.95)),
      ('model', EllipticEnvelope(contamination=0.0017)) ])

  pipeline_ee.fit(X_train)

  labels = pipeline_ee.predict(X_test)
  scores = pipeline_ee.decision_function(X_test)

  y_pred = (labels == -1).astype(int)

  # evaluate
  print(classification_report(y_test, y_pred))
  cm = confusion_matrix(y_test, y_pred)
  print('Confusion matrix:\n',cm)
run_ee()


              precision    recall  f1-score   support

           0       1.00      1.00      1.00     68798
           1       0.00      0.00      0.00       118

    accuracy                           1.00     68916
   macro avg       0.50      0.50      0.50     68916
weighted avg       1.00      1.00      1.00     68916

Confusion matrix:
 [[68683   115]
 [  118     0]]


In [ ]:
def run_IF():

  pipeline = Pipeline([
      ('scaler', StandardScaler()),
      #('pca', PCA(n_components=0.95)),
      ('model', IsolationForest(contamination=0.0017, n_estimators=100)) ])

  pipeline.fit(X_train)

  y_pred = pipeline.predict(X_test)
  y_pred = [0 if x == 1 else 1 for x in y_pred]
  print(classification_report(y_test, y_pred, target_names=['non-fraud', 'fraud']))

  cm = confusion_matrix(y_test, y_pred)
  print('Confusion matrix:\n',cm)

run_IF()


              precision    recall  f1-score   support

   non-fraud       1.00      1.00      1.00     68798
       fraud       0.00      0.00      0.00       118

    accuracy                           1.00     68916
   macro avg       0.50      0.50      0.50     68916
weighted avg       1.00      1.00      1.00     68916

Confusion matrix:
 [[68672   126]
 [  118     0]]


In [ ]:
def run_LOF():

  pipeline = Pipeline([
    ('scaler',StandardScaler()),
    ('model', LocalOutlierFactor(n_neighbors=25,
                                  contamination=0.0017,
                                  novelty=True))
  ])

  pipeline.fit(X_train)

  y_pred = pipeline.predict(X_test)
  y_pred = [0 if x == 1 else 1 for x in y_pred]
  print(classification_report(y_test, y_pred, target_names=['non-fraud', 'fraud']))

  cm = confusion_matrix(y_test, y_pred)
  print('Confusion matrix\n',cm)

run_LOF()


              precision    recall  f1-score   support

   non-fraud       1.00      1.00      1.00     68798
       fraud       0.02      0.02      0.02       118

    accuracy                           1.00     68916
   macro avg       0.51      0.51      0.51     68916
weighted avg       1.00      1.00      1.00     68916

Confusion matrix
 [[68676   122]
 [  116     2]]


In [44]:
from sklearn.cluster import DBSCAN

def run_dbscan():
  pipeline = Pipeline([
    ('scaler',StandardScaler()),
    ('model', DBSCAN(eps=0.7, min_samples=30))
  ])

  y_pred = pipeline.fit_predict(X_test)
  y_pred = np.where(y_pred == -1, 1, 0)

  print(classification_report(y_test, y_pred, target_names=['non-fraud', 'fraud']))

  cm = confusion_matrix(y_test, y_pred)
  print('Confusion matrix\n',cm)

run_dbscan()


              precision    recall  f1-score   support

   non-fraud       1.00      0.99      1.00     68798
       fraud       0.02      0.06      0.02       118

    accuracy                           0.99     68916
   macro avg       0.51      0.53      0.51     68916
weighted avg       1.00      0.99      0.99     68916

Confusion matrix
 [[68351   447]
 [  111     7]]


In [50]:
from sklearn.svm import OneClassSVM
def run_SVM():
    pipeline = Pipeline([
        ('scaler',StandardScaler()),
        ('model', OneClassSVM(kernel='rbf',
                              nu=0.0017))
    ])
    pipeline.fit(X_train)

    y_pred = pipeline.predict(X_test)
    y_pred = np.where(y_pred == -1,1,0)

    print("OneClassSVM parameters:", pipeline.named_steps['model'].get_params())
    print("\nClassification report:")
    print(classification_report(y_test, y_pred, target_names=['non-fraud','fraud']))
    print("Confusion matrix:")
    print(confusion_matrix(y_test, y_pred))
run_SVM()


OneClassSVM parameters: {'cache_size': 200, 'coef0': 0.0, 'degree': 3, 'gamma': 'scale', 'kernel': 'rbf', 'max_iter': -1, 'nu': 0.0017, 'shrinking': True, 'tol': 0.001, 'verbose': False}

Classification report:
              precision    recall  f1-score   support

   non-fraud       1.00      0.98      0.99     68798
       fraud       0.00      0.04      0.01       118

    accuracy                           0.98     68916
   macro avg       0.50      0.51      0.50     68916
weighted avg       1.00      0.98      0.99     68916

Confusion matrix:
[[67680  1118]
 [  113     5]]
